---
title: "lab_8_salmon Linear Regression in R"
author: "Lydia Bleifuss"
date: "11/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
salmon <- read_csv("salmon_imports.csv")
```

```{r}
#exploratory scatterplot

salmon_scatter <- salmon %>% 
  ggplot(aes(x = year, y = salmon_fresh)) +
  geom_point()

salmon_scatter

#Overall, does it look like describing the relationship between year and fresh salmon imports using linear regression makes sense? - YES

#Do you have any concerns about using linear regression to describe the relationship? - CLEAR DIPS IN LINEAR DATA TREND 
```

```{r}
#Linear Regression in R

salmon_model <- lm(salmon_fresh ~ year, data = salmon)
salmon_model

#y = β0 + β1x + ε
#Imports(tons) = 7550 + -14982940(Year)

#???????? Where is the slope here? Is it 7550? Is the intercept the year at -14982940? What is the 25 (from the example in this case?)

# What does the slope mean in the context of this model?
#It's massive and doesn't make sense?

#What does the y-intercept mean in the context of this model? Why is that concerning? 
#Super far is the future and doesn't make sense? 

#What does this mean about extrapolating this model for past values?
#Don't do it because it all is confusing 

```

```{r}
#Model Diagnostics

plot(salmon_model)

#Do residuals appear normally distributed? - Some more than others, need to understand the specifics behind how they work more. The square root on looks good but not the "residuals" one 

#Any concerns about heteroscedasticity or outliers? - Yes fo sho concerns, residuals are looking funky, Cooks distance is something to look at...


  par(mfrow = c(2,2))
  plot(salmon_model)
```

```{r}
#Explore model fit and significance

summary(salmon_model)

#Does year significantly predict salmon imports?
#Yes because p-value: < 2.2e-16 ??

#What does the R2 value actually mean in words?
#Multiple R-squared:  0.9478
#94.8% of variance in salmon imports is explained by year

#What proportion of the variance in salmon imports is NOT explained by year?
#100 - 94.8 = ? Is that right?
#Residual standard error: 14860 on 26 degrees of freedom - does error come into play here? 
```

```{r}
#Prepare a final graph

salmon_final_graph <- ggplot(salmon, aes(x = year, y = salmon_fresh)) + geom_point() +
geom_smooth(method = lm, se = TRUE, size = 0.5, color = "gray20") + theme_bw() +
scale_x_continuous(expand = c(0,0), limits = c(1990, 2017)) +
labs(x = "Year", y = "U.S. Annual Fresh Salmon Imports\n(1,000 pounds)")
salmon_final_graph
```

```{r}
#Make Predictions Using the Model

new_years <- data.frame(year = c(2022, 2024, 2026, 2028))
new_years

#Then feed that data frame into the predict() function, letting it know which model to use to make predictions for the new values.

#Include interval = “confidence” to also report the lower and upper bounds of the 95% CI for model fit at each year

future_predict <- predict(salmon_model, newdata = new_years, interval = "confidence") 
future_predict

#Bind the prediction outcomes (those are the values in column ‘fit’) with the ‘new_years’ data to actually create a useful table of predicted imports and upper and lower CI:

predictions <- data.frame(new_years, future_predict) 
predictions
```

```{r}
#Find Pearson's r (correlation!!!)

salmon_cor <- cor.test(salmon$year, salmon$salmon_fresh)
salmon_cor

#Would you describe this as a weak/strong negative/positive correlation?
#Strong positive? (0.974)

#Concluding statement about the relationship: 

#Year significantly predicts salmon imports (b = 7550, t(26) = 21.7, p < 0.001) with a strong positive correlation between the two (Pearson's r = 0.97).The overall model (Imports(tons) = 7550 + -14982940(Year); units) explains a significant amount of variance in salmon imports (F(1,26) = 472, p < 0.001, R2 = 0.95) 
```

